spring.application.name=demo16


spring.datasource.driver-class-name = com.mysql.jdbc.Driver
spring.datasource.url =  jdbc:mysql://localhost:3306/itKidsSchool
spring.datasource.username = root
spring.datasource.password = yargoro2010
server.port=8081
#spring.datasource.url=  jdbc:mysql://mysql-203d5999-yaroslav-c6ee.l.aivencloud.com:25058/itKids
#spring.datasource.username= avnadmin
#spring.datasource.password = AVNS_3eIbCIu6OLMhwjIkhHT
#server.port=8000
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=itkidsonlineitschool@gmail.com
spring.mail.password=qxwt ezuk vslo aroj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com


# URL для посилань у листах (кнопка адміну)
